%% Instructions Texts %%

%% General Instructions
gen_instr1 = 'Welcome to our experiment! Please, press Enter to read the instructions.';

%% Phase 2 Instructions
ph2_instr1 = strcat('In this experiment you need to choose between two options.\n',...
        'Depending on the symbol you see, a dollar sign or a heart, you have to choose either\n',...
        'the option with a higher chance to win you points or the option you prefer the most out of the two.\n',...
        'Each decision has two phases. Press Enter to continue.');

ph2_instr2 = strcat('In Phase 1, you will see two options on both sides of the screen.\n',...
    'Each option is made up of a colored border and a food item.\n',...
    'The options will be shown on the screen for a short period of time, so try to remember them.\n',...
    'Press Enter to continue.');

ph2_instr3 = strcat('In Phase 2, a dollar sign or a heart symbol will appear on the screen.\n',...
    'If you see the dollar sign, choose the coloured border that has a better chance of winning 100 points.\n',...
    'Please note that: \n',...
    '1. One colour has a better chance to award points than the other.\n',...
    '2. The chance of winning associated with each border may change after each break.\n',...
    '3. Whether you win points is determined by the chance associated with the colour you choose.\n',...
    'Instead, if you see the heart symbol, choose the item you prefer out of the two options.\n',...
    'If your decision is consistent with the preferences given in the ranking task, you will win 100 points.\n',...
    'Your goal is to win as many points as you can.\n',...
    'Press Enter to continue.');

ph2_instr4 = strcat('In Phase 2, you will see the dollar sign or the heart symbol,\n',...
    'but no food items or coloured borders.\n','Press the left or the right key to choose the left or right option.\n',...
    'You have 2.5 seconds to respond after the symbol has appeared.\n',...
    'Do not respond too quickly or too slowly. If you do so, you will receive a warning message.\n',...
    'Press Enter to continue to the practice trials.');

%% Consent form (have to check with JZ)

%% Main_trials instructions
main_trial_instr = 'Now you will start the main task. Press Enter to continue.';

%% Inter_block instructions
inter_block = 'Take a break for a few minutes. Press Enter when you are ready to continue.';

%% Debrief (again check with JZ)
thanks = 'Thank you for participating in the experiment!';
    